---
title: "Musical visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Getting the data

```{r, message=FALSE}
library(tidyverse)
library(here)
library(tuneR)
```

```{r}
if (!file.exists(here('data','sakamoto.mid')))
  download.file('http://www.kunstderfuge.com/-/midi.asp?file=28/mahler_symphony_5_1_(c)boot.mid', here('data', 'sakamoto.mid'))
```

MIDI files contain each note to be played for a song and should contain all information I need for data.

The `tuneR` package has what I was looking for. Read a MIDI file, get a nice data frame in return. The package even gives individual `track`s with names, meaning that I can figure out which instrument plays each note.

```{r}
songs <-  readMidi('./data/sakamoto.mid')
```


```{r}
tracks <- songs %>%
  filter(event == 'Sequence/Track Name') %>%
  transmute(track, track_name = parameterMetaSystem)

notes <- getMidiNotes(songs) %>%
  inner_join(tracks, by = 'track') %>%
  arrange(time) %>%
  head(50)
```

